import { describe, expect, it } from 'vitest'
import {
  DEVICE_NAME_MAX,
  cleanCode,
  cleanDeviceName,
  formatAddedDate,
  groupSecret,
  initialFactorId,
  isCompleteCode,
  isNameTaken,
  isRecentFactor,
  otpauthHref,
  pendingTotp,
  qrImageSrc,
  verifiedTotp,
  withViewBox,
  type TotpFactor,
} from './factors.ts'

const NOW = new Date('2026-10-05T02:00:00Z')
const f = (id: string, created: string, over: Partial<TotpFactor> = {}): TotpFactor => ({
  id,
  friendly_name: `Phone ${id}`,
  factor_type: 'totp',
  status: 'verified',
  created_at: created,
  ...over,
})

describe('device lists', () => {
  it('keeps verified TOTP devices, oldest first', () => {
    const all = [
      f('b', '2026-10-03T00:00:00Z'),
      f('a', '2026-09-01T00:00:00Z'),
      f('c', '2026-10-04T00:00:00Z', { status: 'unverified' }),
      f('d', '2026-10-04T00:00:00Z', { factor_type: 'phone' }),
    ]
    expect(verifiedTotp(all).map((x) => x.id)).toEqual(['a', 'b'])
    expect(pendingTotp(all).map((x) => x.id)).toEqual(['c'])
  })

  it('flags devices added in the last 7 days', () => {
    expect(isRecentFactor('2026-10-04T00:00:00Z', NOW)).toBe(true)
    expect(isRecentFactor('2026-09-28T02:00:01Z', NOW)).toBe(true)
    expect(isRecentFactor('2026-09-28T02:00:00Z', NOW)).toBe(false)
    expect(isRecentFactor('not a date', NOW)).toBe(false)
  })

  it('treats names case-insensitively when checking for duplicates', () => {
    expect(isNameTaken('aina (secretary)', [f('a', '2026-09-01T00:00:00Z', { friendly_name: 'Aina (Secretary)' })])).toBe(true)
    expect(isNameTaken('Hafiz', [f('a', '2026-09-01T00:00:00Z')])).toBe(false)
  })
})

describe('device names', () => {
  it('collapses whitespace and trims', () => {
    expect(cleanDeviceName('  Aina   (Secretary) ')).toEqual({ ok: true, name: 'Aina (Secretary)' })
  })

  it('requires a name, at most 40 characters, without control characters', () => {
    expect(cleanDeviceName('   ')).toEqual({ ok: false, key: 'studio:form.required' })
    expect(cleanDeviceName('x'.repeat(DEVICE_NAME_MAX + 1))).toEqual({ ok: false, key: 'errors:too_long_text' })
    expect(cleanDeviceName('x'.repeat(DEVICE_NAME_MAX)).ok).toBe(true)
    expect(cleanDeviceName('Aina\u0000')).toEqual({ ok: false, key: 'errors:bad_chars' })
  })
})

describe('codes and keys', () => {
  it('accepts pasted codes with spaces or dashes', () => {
    expect(cleanCode('123 456')).toBe('123456')
    expect(cleanCode('123-456-789')).toBe('123456')
    expect(cleanCode('12a3')).toBe('123')
    expect(isCompleteCode('123456')).toBe(true)
    expect(isCompleteCode('12345')).toBe(false)
  })

  it('groups the setup key in fours', () => {
    expect(groupSecret('ABCDEFGHIJKLMNOP')).toBe('ABCD EFGH IJKL MNOP')
    expect(groupSecret('ABCDEF')).toBe('ABCD EF')
  })
})

describe('QR code and otpauth link', () => {
  const svg = '<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"><rect fill="#000000" width="1" height="1"/></svg>'

  const scalable = svg.replace('<svg ', '<svg viewBox="0 0 10 10" ')

  it('percent-encodes the SVG supabase-js returns, so "#" cannot cut the data URL', () => {
    const src = qrImageSrc(`data:image/svg+xml;utf-8,${svg}`)
    expect(src).toBe(`data:image/svg+xml;charset=utf-8,${encodeURIComponent(scalable)}`)
    expect(src).not.toContain('#')
    expect(decodeURIComponent(src!.split(',')[1]!)).toBe(scalable)
  })

  it('also accepts a bare SVG or a base64 image', () => {
    expect(qrImageSrc(svg)).toBe(`data:image/svg+xml;charset=utf-8,${encodeURIComponent(scalable)}`)
    expect(qrImageSrc('data:image/png;base64,iVBORw0KGgo=')).toBe('data:image/png;base64,iVBORw0KGgo=')
  })

  it('adds a viewBox so the QR code scales (Auth only sets width and height)', () => {
    // The shape Supabase Auth (SVGo) really returns.
    const auth = '<?xml version="1.0"?>\n<!-- Generated by SVGo -->\n<svg width="219" height="219"\n     xmlns="http://www.w3.org/2000/svg">\n<rect x="12" y="12" width="3" height="3" style="fill:black"/></svg>'
    expect(withViewBox(auth)).toContain('<svg viewBox="0 0 219 219" width="219" height="219"')
    // The rect's width/height are left alone, and an existing viewBox is kept.
    expect(withViewBox(auth)).toContain('<rect x="12" y="12" width="3" height="3"')
    expect(withViewBox('<svg viewBox="0 0 5 5" width="10" height="10"></svg>')).toBe('<svg viewBox="0 0 5 5" width="10" height="10"></svg>')
    expect(withViewBox('<svg xmlns="x"></svg>')).toBe('<svg xmlns="x"></svg>')
  })

  it('shows nothing for anything else', () => {
    for (const bad of ['', 'javascript:alert(1)', 'https://evil.example/qr.svg', 'data:text/html,<svg>', 'data:image/svg+xml;utf-8,<script>alert(1)</script>']) {
      expect(qrImageSrc(bad)).toBeNull()
    }
  })

  it('links only real otpauth://totp/ URIs', () => {
    const uri = 'otpauth://totp/usmfomo:robotik@usmfomo.pages.dev?issuer=usmfomo&secret=ABCD'
    expect(otpauthHref(uri)).toBe(uri)
    expect(otpauthHref('javascript:alert(1)')).toBeNull()
    expect(otpauthHref('https://example.com/')).toBeNull()
    expect(otpauthHref('otpauth://hotp/x')).toBeNull()
  })
})

describe('labels and choices', () => {
  it('formats the date a device was added in Malaysia time', () => {
    // 20:00 UTC on 4 Oct is already 5 Oct in Malaysia.
    expect(formatAddedDate('2026-10-04T20:00:00Z', 'en')).toBe('5 Oct 2026')
    expect(formatAddedDate('2026-10-04T20:00:00Z', 'ms')).toMatch(/^5 Okt 2026$/)
    expect(formatAddedDate('garbage', 'en')).toBe('')
  })

  it('starts the code form on the only device, or the one last used here', () => {
    const one = [f('a', '2026-09-01T00:00:00Z')]
    const two = [...one, f('b', '2026-09-02T00:00:00Z')]
    expect(initialFactorId(one, null)).toBe('a')
    expect(initialFactorId(one, 'zzz')).toBe('a')
    expect(initialFactorId(two, 'b')).toBe('b')
    // Several devices and nothing (valid) remembered: the person must choose.
    expect(initialFactorId(two, null)).toBeNull()
    expect(initialFactorId(two, 'removed-device')).toBeNull()
    expect(initialFactorId([], 'a')).toBeNull()
  })
})

describe('contact link', async () => {
  const { contactHref } = await import('./contact.ts')
  it('links only https: and mailto: contact channels', () => {
    expect(contactHref(' https://instagram.com/usmfomo ')).toBe('https://instagram.com/usmfomo')
    expect(contactHref('mailto:usmfomo@gmail.com')).toBe('mailto:usmfomo@gmail.com')
    for (const bad of ['', 'http://x.example', 'javascript:alert(1)', 'https://a b']) expect(contactHref(bad)).toBeNull()
  })
})
